apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvtap0
spec: 
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvtap",
      "master": "eth0",
      "mode": "bridge",
      "mtu": 1500
    }'
