apiVersion: v1
kind: Pod
metadata:
  name: samplepod-with-mac-1
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
        {
          "name": "macvtap0",
          "mac": "52:54:00:11:11:11"
        }
    ]'
spec:
  containers:
  - name: samplepod
    command: ["sleep", "99999"]
    image: fedora
